### ISSUE TITLE
Add stopping conditions to `PickIf`

### ISSUE THREAD

**Issue by sylvainhalle** [liflab/synthia#36]
Currently, `PickIf` may run into an infinite loop if the condition that evaluates the events returns false on everything. The purpose of this task is to add a failsafe mechanism to specify when PickIf has the right to stop.

## Maximum number of iterations

A first mechanism to stop `PickIf` is to specify a maximum number of iterations, similar to the `trials` parameter of [JUnit-Quickcheck](https://www.ontestautomation.com/an-introduction-to-property-based-testing-with-junit-quickcheck/).

- [x] Create a new exception type called `GiveUpException`.
- [x] Add an internal member field which, if positive, contains the maximum number of iterations that `PickIf` should try finding a satisfying element (if negative, PickIf should behave as currently and keep trying forever). If the maximum number of iterations is reached, throw a `GiveUpException`.
- [x] Add an alternate constructor where the number of iterations can be specified.
- [x] Make sure that `duplicate` transfers this number to copies of the class.

This behavior is specific to each call to `pick`. The iteration counter restarts from 0 on the next call to `pick`.

## Discard ratio

The second mechanism is to specify what is called the *discard ratio*: the percentage of generated elements that are rejected by the underlying condition. This also mirrors a similar condition in JUnit-Quickcheck (https://pholser.github.io/junit-quickcheck/site/0.8.2/usage/constraining.html, see bottom of document).

- [x] Add an internal `float` member field which, if positive, contains the maximum fraction of generated objects that is allowed to be rejrected by the underlying condition.
- [x] Make sure that `duplicate` transfers this field to copies of the class.
- [x] Add two internal `int` member fields which count the number of objects generated, and the number of objects rejected. If the ratio exceeds the discard ratio, throw a `GiveUpException`.

This behavior is based on the whole history of the object: the discard ratio is the number of elements returned so far, divided by the number of events generated since the object was created. This ratio is reset only on a call to the picker's `reset` method.

**Comment by map555** [comment]
I think `duplicate ` method should be an abstract function for this class. The last point of "Maximum number of iterations" will not be considerated in this issue.

**Comment by map555** [comment]
We could implement the discard ratio as a `Picker<Float>` and store the class in the `ca.uqac.liflab.synthia.util` package.
